### ISSUE TITLE
[DISCOVERY][PHP][CPG] Discovery and CPG generation on PHP files is broken

### ISSUE THREAD

**Issue by mlessio** [testable-eu/sast-tp-framework#57] opened 2023-05-05 09:40 UTC
The discovery phase ends up with an error which seems to be related to the CPG generation.
The issue was noticed while trying to execute the discovery step on a single PHP file.
It is not clear if the issue is related to Joern or to the PHP CPG generation.

The following steps can be performed in order to reproduce the issue:

- create a new directory with a single PHP file inside it (for simplicity, we used 1_instance_1_static_variables.php test file contained in the testability_patterns repository, reported also below)
- execute the discovery on that folder, with the following command:
```
tpframework discovery -a -t testphp/ -l PHP
```

Test file:
```
<?php

function F($a){
    static $b = 'abc'; // tarpit
    echo $b; // sink (moved out from standard skeleton)
    $b = $a;
}

$a = $_GET["p1"];  // source
F($a); // print "abc"
F('abc'); // print value of $_GET["p1"]
```

The following error message gets triggered after a few seconds:
```
Discovery for patterns started...
09:19 - INFO - Discovery for patterns started...
09:19 - INFO - Generation of CPG for testphp: started...
2023-05-05 09:19:48.433Z  info [PhpToCpg] Dominator(s) done.  - (PhpToCpg.scala:142)
2023-05-05 09:19:48.487Z  info [PhpToCpg] DDG done.  - (PhpToCpg.scala:148)
2023-05-05 09:19:48.519Z  info [PhpToCpg] Stub creation done.  - (PhpToCpg.scala:204)
2023-05-05 09:19:48.544Z  info [PhpToCpg] Call finishing pass done.  - (PhpToCpg.scala:218)
executing /tp-framework/tp_framework/core/cpgTest.sc with params=Map(name -> /tp-framework/out/discovery_2023-05-05-09-19-46_PHP_testphp/cpg_2023-05-05-09-19-46_PHP_testphp.bin)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/joern/joern-cli/lib/joernext-querydb-io.joern.ghidra-10.2.3_PUBLIC_20230208.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/joern/joern-cli/lib/org.apache.logging.log4j.log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
Compiling (synthetic)/ammonite/predef/CodePredef.sc
Exception in thread "main" java.lang.AssertionError: script errored: 
	at io.joern.console.ScriptExecution.runScript(BridgeBase.scala:243)
	at io.joern.console.ScriptExecution.runScript$(BridgeBase.scala:224)
	at io.joern.joerncli.console.AmmoniteBridge$.runScript(AmmoniteBridge.scala:5)
	at io.joern.console.BridgeBase.runAmmonite(BridgeBase.scala:167)
	at io.joern.console.BridgeBase.runAmmonite$(BridgeBase.scala:148)
	at io.joern.joerncli.console.AmmoniteBridge$.runAmmonite(AmmoniteBridge.scala:5)
	at io.joern.joerncli.console.AmmoniteBridge$.delayedEndpoint$io$joern$joerncli$console$AmmoniteBridge$1(AmmoniteBridge.scala:7)
	at io.joern.joerncli.console.AmmoniteBridge$delayedInit$body.apply(AmmoniteBridge.scala:5)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.joern.joerncli.console.AmmoniteBridge$.main(AmmoniteBridge.scala:5)
	at io.joern.joerncli.console.AmmoniteBridge.main(AmmoniteBridge.scala)
Caused by: java.lang.NoSuchMethodError: 'void io.joern.dataflowengineoss.layers.dataflows.OssDataFlowOptions.<init>(int)'
	at io.joern.joerncli.console.JoernConsole.<init>(JoernConsole.scala:30)
	at io.joern.joerncli.console.Joern$.<init>(Joern.scala:3)
	at io.joern.joerncli.console.Joern$.<clinit>(Joern.scala:3)
	at ammonite.predef.CodePredef$.<clinit>(CodePredef.sc:227)
	at ammonite.predef.CodePredef.$main(CodePredef.sc)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$evalMain$1(Evaluator.scala:108)
	at ammonite.util.Util$.withContextClassloader(Util.scala:24)
	at ammonite.runtime.Evaluator$$anon$1.evalMain(Evaluator.scala:90)
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$processScriptBlock$1(Evaluator.scala:153)
	at ammonite.util.Catching.map(Res.scala:117)
	at ammonite.runtime.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:150)
	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$5(Interpreter.scala:344)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$4(Interpreter.scala:335)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$2(Interpreter.scala:329)
	at ammonite.util.Catching.flatMap(Res.scala:115)
	at ammonite.interp.Interpreter.processSingleBlock(Interpreter.scala:328)
	at ammonite.interp.Interpreter.$anonfun$processModule$8(Interpreter.scala:412)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$3(Interpreter.scala:540)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:526)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:587)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:584)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:581)
	at scala.Option.getOrElse(Option.scala:201)
	at ammonite.interp.Interpreter.loop$1(Interpreter.scala:581)
	at ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:619)
	at ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:414)
	at ammonite.util.Catching.flatMap(Res.scala:115)
	at ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:405)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.processModule(Interpreter.scala:395)
	at ammonite.interp.Interpreter.$anonfun$initializePredef$3(Interpreter.scala:148)
	at ammonite.interp.Interpreter.$anonfun$initializePredef$3$adapted(Interpreter.scala:148)
	at ammonite.interp.PredefInitialization$.$anonfun$apply$2(PredefInitialization.scala:79)
	at ammonite.util.Res$.$anonfun$fold$1(Res.scala:32)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at ammonite.util.Res$.fold(Res.scala:30)
	at ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:67)
	at ammonite.interp.Interpreter.initializePredef(Interpreter.scala:150)
	at ammonite.Main.$anonfun$instantiateInterpreter$1(Main.scala:202)
	at scala.util.Either$RightProjection.flatMap(Either.scala:757)
	at ammonite.Main.instantiateInterpreter(Main.scala:159)
	at ammonite.Main.runScript(Main.scala:250)
	at io.joern.console.ScriptExecution.runScript(BridgeBase.scala:235)
	... 19 more
09:19 - ERROR - Error while generating CPG for source.
Traceback (most recent call last):
  File "/tp-framework/tp_framework/core/discovery.py", line 71, in generate_cpg
    cpg_gen_test_result: str = run_joern_scala_query_for_test(joern_scala_query_for_test_cmd)
  File "/tp-framework/tp_framework/core/discovery.py", line 89, in run_joern_scala_query_for_test
    output = subprocess.check_output(joern_scala_query_for_test_cmd, shell=True).decode('utf-8-sig')
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'joern --script /tp-framework/tp_framework/core/cpgTest.sc --params name=/tp-framework/out/discovery_2023-05-05-09-19-46_PHP_testphp/cpg_2023-05-05-09-19-46_PHP_testphp.bin' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/tp-framework/tp_framework/core/discovery.py", line 71, in generate_cpg
    cpg_gen_test_result: str = run_joern_scala_query_for_test(joern_scala_query_for_test_cmd)
  File "/tp-framework/tp_framework/core/discovery.py", line 89, in run_joern_scala_query_for_test
    output = subprocess.check_output(joern_scala_query_for_test_cmd, shell=True).decode('utf-8-sig')
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'joern --script /tp-framework/tp_framework/core/cpgTest.sc --params name=/tp-framework/out/discovery_2023-05-05-09-19-46_PHP_testphp/cpg_2023-05-05-09-19-46_PHP_testphp.bin' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tpframework", line 33, in <module>
    sys.exit(load_entry_point('tp-framework', 'console_scripts', 'tpframework')())
  File "/tp-framework/tp_framework/cli/main.py", line 46, in main
    discovery_pattern_cmd.execute_command(args)
  File "/tp-framework/tp_framework/cli/tpf_commands.py", line 263, in execute_command
    interface.run_discovery_for_pattern_list(target_dir, l_pattern_id, language, tool_parsed, tp_lib_path,
  File "/tp-framework/tp_framework/cli/interface.py", line 74, in run_discovery_for_pattern_list
    d_res = discovery.discovery(Path(src_dir), pattern_id_list, tp_lib_path, itools, language, build_name,
  File "/tp-framework/tp_framework/core/discovery.py", line 260, in discovery
    cpg: Path = generate_cpg(src_dir, language, build_name, disc_output_dir, timeout_sec=timeout_sec)
  File "/tp-framework/tp_framework/core/discovery.py", line 81, in generate_cpg
    raise rs
core.exceptions.CPGGenerationError: Error while generating CPG for source.
```

**Comment by mlessio** [comment] 2023-05-05 11:41
Quick update from my side, it seems that bumping the Joern version to the one mentioned in @pr0me PR, solves the issue.
The command to be executed inside the container is the following:
```./joern-install.sh --version=v1.1.1684 --install-dir=/opt/joern --reinstall```

**Comment by compaluca** [comment] 2023-05-09 09:30
That pull request is now accepted and merged. However the version of Joern used in that pull request is `v1.1.1538` and not `v1.1.1684`. @mlessio: can you please check if the problem is still in place?

**Comment by mlessio** [comment] 2023-05-09 10:55
@compaluca i just tried by manually installing v1.1.1538 and unfortunately it has the same problem reported above.

**Comment by pr0me** [comment] 2023-05-10 09:03
yes, pretty sure we can just bump the version to the most recent one.
Currently don't have the time for extensive testing, but I've recently used joern on other projects quite extensively and the jssrc frontend is also very robust by now.

I would recommend to change the install command to the most recent version and then merge.
If issues arise, please open a new issue and tag me in it.

**Closed** 2023-06-30 13:57 UTC
Labels: bug
